<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.9.5</Version>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AutoContext.Engine.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AutoContext.Engine.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoContext.Framework.Pipes\AutoContext.Framework.Pipes.csproj" />
    <ProjectReference Include="..\AutoContext.Engine.Protocol\AutoContext.Engine.Protocol.csproj" />
    <ProjectReference Include="..\AutoContext.Instructions.Parser\AutoContext.Instructions.Parser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" Version="9.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
  </ItemGroup>

</Project>
