import type { ToggleEntry } from './toggle-entry.js';

const settingIdPrefix = 'sharppilot.instructions.';
const overrideContextPrefix = 'sharppilot.override.';

export function overrideContextKey(settingId: string): string {
    return overrideContextPrefix + settingId.slice(settingIdPrefix.length);
}

const entryContextKeys = new Map<string, readonly string[]>([
    ['sharppilot.instructions.docker', ['hasDocker']],
    ['sharppilot.instructions.graphql', ['hasGraphql']],
    ['sharppilot.instructions.dotnet.aspnetCore', ['hasAspNetCore']],
    ['sharppilot.instructions.dotnet.asyncAwait', ['hasDotnet']],
    ['sharppilot.instructions.dotnet.blazor', ['hasBlazor']],
    ['sharppilot.instructions.dotnet.codingStandards', ['hasDotnet']],
    ['sharppilot.instructions.dotnet.core', ['hasDotnet']],
    ['sharppilot.instructions.dotnet.dapper', ['hasDapper']],
    ['sharppilot.instructions.dotnet.debugging', ['hasDotnet']],
    ['sharppilot.instructions.dotnet.entityFrameworkCore', ['hasEntityFrameworkCore']],
    ['sharppilot.instructions.dotnet.grpc', ['hasGrpc']],
    ['sharppilot.instructions.dotnet.maui', ['hasMaui']],
    ['sharppilot.instructions.dotnet.mediatorCqrs', ['hasMediatR']],
    ['sharppilot.instructions.dotnet.mongodb', ['hasMongodb']],
    ['sharppilot.instructions.dotnet.mysql', ['hasMysql']],
    ['sharppilot.instructions.dotnet.nuget', ['hasDotnet']],
    ['sharppilot.instructions.dotnet.oracle', ['hasOracle']],
    ['sharppilot.instructions.dotnet.performanceMemory', ['hasDotnet']],
    ['sharppilot.instructions.dotnet.postgresql', ['hasPostgres']],
    ['sharppilot.instructions.dotnet.razor', ['hasBlazor']],
    ['sharppilot.instructions.dotnet.redis', ['hasRedis']],
    ['sharppilot.instructions.dotnet.signalR', ['hasSignalR']],
    ['sharppilot.instructions.dotnet.sqlite', ['hasSqlite']],
    ['sharppilot.instructions.dotnet.sqlServer', ['hasSqlServer']],
    ['sharppilot.instructions.dotnet.testing', ['hasDotnet']],
    ['sharppilot.instructions.dotnet.unity', ['hasUnity']],
    ['sharppilot.instructions.dotnet.winForms', ['hasWinForms']],
    ['sharppilot.instructions.dotnet.wpf', ['hasWpf']],
    ['sharppilot.instructions.dotnet.xunit', ['hasXunit']],
    ['sharppilot.instructions.dotnet.mstest', ['hasMstest']],
    ['sharppilot.instructions.dotnet.nunit', ['hasNunit']],
    ['sharppilot.instructions.dotnet.csharp.codingStyle', ['hasDotnet']],
    ['sharppilot.instructions.dotnet.fsharp.codingStyle', ['hasFsharp']],
    ['sharppilot.instructions.dotnet.vbnet.codingStyle', ['hasVbnet']],
    ['sharppilot.instructions.git.commitFormat', ['hasGit']],
    ['sharppilot.instructions.scripting.powershell', ['hasPowerShell']],
    ['sharppilot.instructions.scripting.bash', ['hasBash']],
    ['sharppilot.instructions.scripting.batch', ['hasBatch']],
    ['sharppilot.instructions.web.angular', ['hasAngular']],
    ['sharppilot.instructions.web.css', ['hasCss']],
    ['sharppilot.instructions.web.html', ['hasHtml']],
    ['sharppilot.instructions.web.javascript', ['hasJavaScript', 'hasTypeScript']],
    ['sharppilot.instructions.web.nextJs', ['hasNextJs']],
    ['sharppilot.instructions.web.nodeJs', ['hasNodeJs']],
    ['sharppilot.instructions.web.react', ['hasReact']],
    ['sharppilot.instructions.web.svelte', ['hasSvelte']],
    ['sharppilot.instructions.web.typescript', ['hasTypeScript']],
    ['sharppilot.instructions.web.vue', ['hasVue']],
    ['sharppilot.instructions.web.testing', ['hasWebTesting']],
    ['sharppilot.instructions.web.vitest', ['hasVitest']],
    ['sharppilot.instructions.web.jest', ['hasJest']],
    ['sharppilot.instructions.web.jasmine', ['hasJasmine']],
    ['sharppilot.instructions.web.mocha', ['hasMocha']],
    ['sharppilot.instructions.web.playwright', ['hasPlaywright']],
    ['sharppilot.instructions.web.cypress', ['hasCypress']],
    ['sharppilot.tools.check_csharp_async_patterns', ['hasDotnet']],
    ['sharppilot.tools.check_csharp_coding_style', ['hasDotnet']],
    ['sharppilot.tools.check_csharp_member_ordering', ['hasDotnet']],
    ['sharppilot.tools.check_csharp_naming_conventions', ['hasDotnet']],
    ['sharppilot.tools.check_csharp_nullable_context', ['hasDotnet']],
    ['sharppilot.tools.check_csharp_project_structure', ['hasDotnet']],
    ['sharppilot.tools.check_csharp_test_style', ['hasDotnet']],
    ['sharppilot.tools.check_nuget_hygiene', ['hasDotnet']],
    ['sharppilot.tools.check_git_commit_content', ['hasGit']],
    ['sharppilot.tools.check_git_commit_format', ['hasGit']],
]);

export function contextKeysForEntry(entry: ToggleEntry): readonly string[] {
    return entryContextKeys.get(entry.settingId) ?? [];
}
