import type { McpToolEntry } from './mcp-tool-entry.js';
import type { InstructionsFileEntry } from './instructions-catalog-entry.js';

// Category order: General → Languages → Platforms (.NET, Web) → Tools.
// Within each category, entries are sorted alphabetically by label.
// package.json (chatInstructions + configuration.properties) should follow the same order.
export const instructionEntries: readonly InstructionsFileEntry[] = [
    { settingId: 'sharppilot.instructions.codeReview', fileName: 'code-review.instructions.md', label: 'Code Review', category: 'General' },
    { settingId: 'sharppilot.instructions.designPrinciples', fileName: 'design-principles.instructions.md', label: 'Design Principles', category: 'General' },
    { settingId: 'sharppilot.instructions.restApiDesign', fileName: 'rest-api-design.instructions.md', label: 'REST API Design', category: 'General' },
    { settingId: 'sharppilot.instructions.testing', fileName: 'testing.instructions.md', label: 'Testing', category: 'General', contextKeys: ['hasDotNetTesting', 'hasWebTesting'] },
    { settingId: 'sharppilot.instructions.lang.bash', fileName: 'lang-bash.instructions.md', label: 'Bash', category: 'Languages', contextKeys: ['hasBash'] },
    { settingId: 'sharppilot.instructions.lang.batch', fileName: 'lang-batch.instructions.md', label: 'Batch (CMD)', category: 'Languages', contextKeys: ['hasBatch'] },
    { settingId: 'sharppilot.instructions.lang.c', fileName: 'lang-c.instructions.md', label: 'C', category: 'Languages', contextKeys: ['hasC'] },
    { settingId: 'sharppilot.instructions.lang.csharp', fileName: 'lang-csharp.instructions.md', label: 'C#', category: 'Languages', contextKeys: ['hasCSharp'] },
    { settingId: 'sharppilot.instructions.lang.cpp', fileName: 'lang-cpp.instructions.md', label: 'C++', category: 'Languages', contextKeys: ['hasCpp'] },
    { settingId: 'sharppilot.instructions.lang.css', fileName: 'lang-css.instructions.md', label: 'CSS', category: 'Languages', contextKeys: ['hasCss'] },
    { settingId: 'sharppilot.instructions.lang.fsharp', fileName: 'lang-fsharp.instructions.md', label: 'F#', category: 'Languages', contextKeys: ['hasFSharp'] },
    { settingId: 'sharppilot.instructions.lang.go', fileName: 'lang-go.instructions.md', label: 'Go', category: 'Languages', contextKeys: ['hasGo'] },
    { settingId: 'sharppilot.instructions.lang.graphql', fileName: 'lang-graphql.instructions.md', label: 'GraphQL', category: 'Languages', contextKeys: ['hasGraphql'] },
    { settingId: 'sharppilot.instructions.lang.groovy', fileName: 'lang-groovy.instructions.md', label: 'Groovy', category: 'Languages', contextKeys: ['hasGroovy'] },
    { settingId: 'sharppilot.instructions.lang.html', fileName: 'lang-html.instructions.md', label: 'HTML', category: 'Languages', contextKeys: ['hasHtml'] },
    { settingId: 'sharppilot.instructions.lang.java', fileName: 'lang-java.instructions.md', label: 'Java', category: 'Languages', contextKeys: ['hasJava'] },
    { settingId: 'sharppilot.instructions.lang.javascript', fileName: 'lang-javascript.instructions.md', label: 'JavaScript', category: 'Languages', contextKeys: ['hasJavaScript', 'hasTypeScript'] },
    { settingId: 'sharppilot.instructions.lang.kotlin', fileName: 'lang-kotlin.instructions.md', label: 'Kotlin', category: 'Languages', contextKeys: ['hasKotlin'] },
    { settingId: 'sharppilot.instructions.lang.lua', fileName: 'lang-lua.instructions.md', label: 'Lua', category: 'Languages', contextKeys: ['hasLua'] },
    { settingId: 'sharppilot.instructions.lang.php', fileName: 'lang-php.instructions.md', label: 'PHP', category: 'Languages', contextKeys: ['hasPhp'] },
    { settingId: 'sharppilot.instructions.lang.powershell', fileName: 'lang-powershell.instructions.md', label: 'PowerShell', category: 'Languages', contextKeys: ['hasPowerShell'] },
    { settingId: 'sharppilot.instructions.lang.python', fileName: 'lang-python.instructions.md', label: 'Python', category: 'Languages', contextKeys: ['hasPython'] },
    { settingId: 'sharppilot.instructions.lang.rust', fileName: 'lang-rust.instructions.md', label: 'Rust', category: 'Languages', contextKeys: ['hasRust'] },
    { settingId: 'sharppilot.instructions.lang.scala', fileName: 'lang-scala.instructions.md', label: 'Scala', category: 'Languages', contextKeys: ['hasScala'] },
    { settingId: 'sharppilot.instructions.lang.sql', fileName: 'lang-sql.instructions.md', label: 'SQL', category: 'Languages' },
    { settingId: 'sharppilot.instructions.lang.typescript', fileName: 'lang-typescript.instructions.md', label: 'TypeScript', category: 'Languages', contextKeys: ['hasTypeScript'] },
    { settingId: 'sharppilot.instructions.lang.vbnet', fileName: 'lang-vbnet.instructions.md', label: 'VB.NET', category: 'Languages', contextKeys: ['hasVbNet'] },
    { settingId: 'sharppilot.instructions.lang.yaml', fileName: 'lang-yaml.instructions.md', label: 'YAML', category: 'Languages', contextKeys: ['hasYaml'] },
    { settingId: 'sharppilot.instructions.dotnet.maui', fileName: 'dotnet-maui.instructions.md', label: '.NET MAUI', category: '.NET', contextKeys: ['hasMaui'] },
    { settingId: 'sharppilot.instructions.dotnet.aspnetCore', fileName: 'dotnet-aspnetcore.instructions.md', label: 'ASP.NET Core', category: '.NET', contextKeys: ['hasAspNetCore'] },
    { settingId: 'sharppilot.instructions.dotnet.aspx', fileName: 'dotnet-aspx.instructions.md', label: 'ASP.NET Web Forms', category: '.NET', contextKeys: ['hasWebForms'] },
    { settingId: 'sharppilot.instructions.dotnet.asyncAwait', fileName: 'dotnet-async-await.instructions.md', label: 'Async/Await', category: '.NET', contextKeys: ['hasDotNet'] },
    { settingId: 'sharppilot.instructions.dotnet.blazor', fileName: 'dotnet-blazor.instructions.md', label: 'Blazor', category: '.NET', contextKeys: ['hasBlazor'] },
    { settingId: 'sharppilot.instructions.dotnet.codingStandards', fileName: 'dotnet-coding-standards.instructions.md', label: 'Coding Standards', category: '.NET', contextKeys: ['hasDotNet'] },
    { settingId: 'sharppilot.instructions.dotnet.core', fileName: 'dotnet-core.instructions.md', label: 'Core (DI, Logging, Config, Security)', category: '.NET', contextKeys: ['hasDotNet'] },
    { settingId: 'sharppilot.instructions.dotnet.dapper', fileName: 'dotnet-dapper.instructions.md', label: 'Dapper', category: '.NET', contextKeys: ['hasDapper'] },
    { settingId: 'sharppilot.instructions.dotnet.debugging', fileName: 'dotnet-debugging.instructions.md', label: 'Debugging', category: '.NET', contextKeys: ['hasDotNet'] },
    { settingId: 'sharppilot.instructions.dotnet.entityFrameworkCore', fileName: 'dotnet-entity-framework-core.instructions.md', label: 'Entity Framework Core', category: '.NET', contextKeys: ['hasEntityFrameworkCore'] },
    { settingId: 'sharppilot.instructions.dotnet.grpc', fileName: 'dotnet-grpc.instructions.md', label: 'gRPC', category: '.NET', contextKeys: ['hasGrpc'] },
    { settingId: 'sharppilot.instructions.dotnet.mediatorCqrs', fileName: 'dotnet-mediator-cqrs.instructions.md', label: 'Mediator / CQRS', category: '.NET', contextKeys: ['hasMediatR'] },
    { settingId: 'sharppilot.instructions.dotnet.mongodb', fileName: 'dotnet-mongodb.instructions.md', label: 'MongoDB', category: '.NET', contextKeys: ['hasMongoDb'] },
    { settingId: 'sharppilot.instructions.dotnet.mstest', fileName: 'dotnet-mstest.instructions.md', label: 'MSTest', category: '.NET', contextKeys: ['hasMsTest'] },
    { settingId: 'sharppilot.instructions.dotnet.mysql', fileName: 'dotnet-mysql.instructions.md', label: 'MySQL', category: '.NET', contextKeys: ['hasMySql'] },
    { settingId: 'sharppilot.instructions.dotnet.nuget', fileName: 'dotnet-nuget.instructions.md', label: 'NuGet', category: '.NET', contextKeys: ['hasDotNet'] },
    { settingId: 'sharppilot.instructions.dotnet.nunit', fileName: 'dotnet-nunit.instructions.md', label: 'NUnit', category: '.NET', contextKeys: ['hasNUnit'] },
    { settingId: 'sharppilot.instructions.dotnet.oracle', fileName: 'dotnet-oracle.instructions.md', label: 'Oracle', category: '.NET', contextKeys: ['hasOracle'] },
    { settingId: 'sharppilot.instructions.dotnet.performanceMemory', fileName: 'dotnet-performance-memory.instructions.md', label: 'Performance & Memory', category: '.NET', contextKeys: ['hasDotNet'] },
    { settingId: 'sharppilot.instructions.dotnet.postgresql', fileName: 'dotnet-postgresql.instructions.md', label: 'PostgreSQL', category: '.NET', contextKeys: ['hasPostgres'] },
    { settingId: 'sharppilot.instructions.dotnet.razor', fileName: 'dotnet-razor.instructions.md', label: 'Razor', category: '.NET', contextKeys: ['hasRazor'] },
    { settingId: 'sharppilot.instructions.dotnet.redis', fileName: 'dotnet-redis.instructions.md', label: 'Redis', category: '.NET', contextKeys: ['hasRedis'] },
    { settingId: 'sharppilot.instructions.dotnet.signalR', fileName: 'dotnet-signalr.instructions.md', label: 'SignalR', category: '.NET', contextKeys: ['hasSignalR'] },
    { settingId: 'sharppilot.instructions.dotnet.sqlServer', fileName: 'dotnet-sql-server.instructions.md', label: 'SQL Server', category: '.NET', contextKeys: ['hasSqlServer'] },
    { settingId: 'sharppilot.instructions.dotnet.sqlite', fileName: 'dotnet-sqlite.instructions.md', label: 'SQLite', category: '.NET', contextKeys: ['hasSqlite'] },
    { settingId: 'sharppilot.instructions.dotnet.testing', fileName: 'dotnet-testing.instructions.md', label: 'Testing', category: '.NET', contextKeys: ['hasDotNetTesting'] },
    { settingId: 'sharppilot.instructions.dotnet.unity', fileName: 'dotnet-unity.instructions.md', label: 'Unity', category: '.NET', contextKeys: ['hasUnity'] },
    { settingId: 'sharppilot.instructions.dotnet.winForms', fileName: 'dotnet-winforms.instructions.md', label: 'Windows Forms', category: '.NET', contextKeys: ['hasWinForms'] },
    { settingId: 'sharppilot.instructions.dotnet.wpf', fileName: 'dotnet-wpf.instructions.md', label: 'WPF', category: '.NET', contextKeys: ['hasWpf'] },
    { settingId: 'sharppilot.instructions.dotnet.xaml', fileName: 'dotnet-xaml.instructions.md', label: 'XAML', category: '.NET', contextKeys: ['hasXaml'] },
    { settingId: 'sharppilot.instructions.dotnet.xunit', fileName: 'dotnet-xunit.instructions.md', label: 'xUnit', category: '.NET', contextKeys: ['hasXunit'] },
    { settingId: 'sharppilot.instructions.web.angular', fileName: 'web-angular.instructions.md', label: 'Angular', category: 'Web', contextKeys: ['hasAngular'] },
    { settingId: 'sharppilot.instructions.web.cypress', fileName: 'web-cypress.instructions.md', label: 'Cypress', category: 'Web', contextKeys: ['hasCypress'] },
    { settingId: 'sharppilot.instructions.web.jasmine', fileName: 'web-jasmine.instructions.md', label: 'Jasmine', category: 'Web', contextKeys: ['hasJasmine'] },
    { settingId: 'sharppilot.instructions.web.jest', fileName: 'web-jest.instructions.md', label: 'Jest', category: 'Web', contextKeys: ['hasJest'] },
    { settingId: 'sharppilot.instructions.web.mocha', fileName: 'web-mocha.instructions.md', label: 'Mocha', category: 'Web', contextKeys: ['hasMocha'] },
    { settingId: 'sharppilot.instructions.web.nextJs', fileName: 'web-nextjs.instructions.md', label: 'Next.js', category: 'Web', contextKeys: ['hasNextJs'] },
    { settingId: 'sharppilot.instructions.web.nodeJs', fileName: 'web-nodejs.instructions.md', label: 'Node.js', category: 'Web', contextKeys: ['hasNodeJs'] },
    { settingId: 'sharppilot.instructions.web.playwright', fileName: 'web-playwright.instructions.md', label: 'Playwright', category: 'Web', contextKeys: ['hasPlaywright'] },
    { settingId: 'sharppilot.instructions.web.react', fileName: 'web-react.instructions.md', label: 'React', category: 'Web', contextKeys: ['hasReact'] },
    { settingId: 'sharppilot.instructions.web.svelte', fileName: 'web-svelte.instructions.md', label: 'Svelte', category: 'Web', contextKeys: ['hasSvelte'] },
    { settingId: 'sharppilot.instructions.web.testing', fileName: 'web-testing.instructions.md', label: 'Testing', category: 'Web', contextKeys: ['hasWebTesting'] },
    { settingId: 'sharppilot.instructions.web.vitest', fileName: 'web-vitest.instructions.md', label: 'Vitest', category: 'Web', contextKeys: ['hasVitest'] },
    { settingId: 'sharppilot.instructions.web.vue', fileName: 'web-vue.instructions.md', label: 'Vue.js', category: 'Web', contextKeys: ['hasVue'] },
    { settingId: 'sharppilot.instructions.git.commitFormat', fileName: 'git-commit-format.instructions.md', label: 'Commit Format', category: 'Tools', contextKeys: ['hasGit'] },
    { settingId: 'sharppilot.instructions.docker', fileName: 'docker.instructions.md', label: 'Docker', category: 'Tools', contextKeys: ['hasDocker'] },
];

export const instructionsCategoryOrder: readonly string[] = ['General', 'Languages', '.NET', 'Web', 'Tools'];

export const mcpToolEntries: readonly McpToolEntry[] = [
    { settingId: 'sharppilot.tools.check_csharp_async_patterns', featureName: 'check_csharp_async_patterns', toolName: 'check_csharp_all', label: 'Async Patterns', category: 'C#', group: '.NET', contextKeys: ['hasCSharp'] },
    { settingId: 'sharppilot.tools.check_csharp_coding_style', featureName: 'check_csharp_coding_style', toolName: 'check_csharp_all', label: 'Coding Style', category: 'C#', group: '.NET', contextKeys: ['hasCSharp'] },
    { settingId: 'sharppilot.tools.check_csharp_member_ordering', featureName: 'check_csharp_member_ordering', toolName: 'check_csharp_all', label: 'Member Ordering', category: 'C#', group: '.NET', contextKeys: ['hasCSharp'] },
    { settingId: 'sharppilot.tools.check_csharp_naming_conventions', featureName: 'check_csharp_naming_conventions', toolName: 'check_csharp_all', label: 'Naming Conventions', category: 'C#', group: '.NET', contextKeys: ['hasCSharp'] },
    { settingId: 'sharppilot.tools.check_csharp_nullable_context', featureName: 'check_csharp_nullable_context', toolName: 'check_csharp_all', label: 'Nullable Context', category: 'C#', group: '.NET', contextKeys: ['hasCSharp'] },
    { settingId: 'sharppilot.tools.check_csharp_project_structure', featureName: 'check_csharp_project_structure', toolName: 'check_csharp_all', label: 'Project Structure', category: 'C#', group: '.NET', contextKeys: ['hasCSharp'] },
    { settingId: 'sharppilot.tools.check_csharp_test_style', featureName: 'check_csharp_test_style', toolName: 'check_csharp_all', label: 'Test Style', category: 'C#', group: '.NET', contextKeys: ['hasCSharp'] },
    { settingId: 'sharppilot.tools.check_nuget_hygiene', toolName: 'check_nuget_hygiene', label: 'NuGet Hygiene', category: 'NuGet', group: '.NET', contextKeys: ['hasDotNet'] },
    { settingId: 'sharppilot.tools.check_git_commit_content', featureName: 'check_git_commit_content', toolName: 'check_git_all', label: 'Commit Content', category: 'Git', group: 'Workspace', contextKeys: ['hasGit'] },
    { settingId: 'sharppilot.tools.check_git_commit_format', featureName: 'check_git_commit_format', toolName: 'check_git_all', label: 'Commit Format', category: 'Git', group: 'Workspace', contextKeys: ['hasGit'] },
    { settingId: 'sharppilot.tools.get_editorconfig', toolName: 'get_editorconfig', label: 'EditorConfig', category: 'EditorConfig', group: 'Workspace' },
    { settingId: 'sharppilot.tools.check_typescript_coding_style', featureName: 'check_typescript_coding_style', toolName: 'check_typescript_all', label: 'Coding Style', category: 'TypeScript', group: 'Web', contextKeys: ['hasTypeScript'] },
];

export const mcpToolGroupOrder: readonly string[] = ['.NET', 'Web', 'Workspace'];
export const mcpToolCategoryOrder: readonly string[] = ['C#', 'NuGet', 'TypeScript', 'Git', 'EditorConfig'];
